Chapter code common library
vulkano-rs/vulkano-www pull request #109
Opened 2022-03-15 18:29 UTC by ZakStar17

I created a common library that may remove some of the repeated code and make everything easier to update.

Next, my plans are to update the guide to Vulkano 0.29 and then start working on the new chapter focused on buffers (some of the code is already there).

2022-03-16 17:14 UTC, hakolao requested changes
Hey, this is great! Well done 👍 

Just one minor problem, which is easy to fix:
On my macbook (I generally use Linux, but today just happen to be on my mac) the example `images`, `graphics_pipeline`, `compute_pipeline` and `buffer_creation` fails to `ExtensionRestrictionNotMet(ExtensionRestrictionError { extension: "khr_portability_subset", restriction: RequiredIfSupported })`.

This could be fixed with:
```rust
let device_extensions = DeviceExtensions::none();
&physical.required_extensions().union(&device_extensions)
```

I'd assume using this is best practice anyway.

Other than that, I just put there some questions for my own learning purposes. And two minor code suggestions. Interesting to also see different `Renderer` approaches than my own.

2022-03-16 17:14 UTC, hakolao commented on chapter_code/src/vulkano_objects/swapchain.rs
> +    .num_images(caps.min_image_count + 1)
Any reason to use `+1` here? My apps have been fine with just the `min_image_count`.

2022-03-16 17:18 UTC, hakolao commented on chapter_code/src/vulkano_objects/swapchain.rs
> +    .num_images(caps.min_image_count + 1)
Asking, because I don't know.

2022-03-19 17:26 UTC, ZakStar17 commented on chapter_code/src/lib.rs
> +}
I implemented your code, it looks cleaner in my opinion

2022-03-19 17:42 UTC, ZakStar17 commented on chapter_code/src/bin/more_on_buffers/render/renderer.rs
> +pub type Fence = FenceSignalFuture<
I tested with `Box<dyn GpuFuture>`, but I couldn't find a way to make it work with multiple frames in flight. Because I only wanted to wait for the oldest fence to finish, I couldn't just use `.cleanup_finished()` (as I needed to know if the submission actually finished or not to know when could I reuse the resources) so the cleanes option I found is to use `.wait()` that is implemented on `vulkano::sync::FenceSignalFuture`.
However, to use that method (that isn't a trait implementation) I somehow needed to tell Rust to remember that the future will signal a fence, and for that I needed to save the entire type of the future (with all the stuff that didn't really matter), so that I latter could set everything easily in the loop.

I don't like that much how it turned out, but I tested different things and this seemed the best approach.

2022-03-19 17:44 UTC, hakolao commented on chapter_code/src/bin/more_on_buffers/render/renderer.rs
> +pub type Fence = FenceSignalFuture<
Okay :)

2022-03-19 17:55 UTC, ZakStar17 commented on chapter_code/src/shaders/movable_square/vertex.glsl
> +} uniforms;
I don't really have a high Vulkan background, so I am learning at the same time as I write the tutorials. I didn't actually knew about push constants, but as I am seeing right now (https://stackoverflow.com/questions/50956414/what-is-a-push-constant-in-vulkan) they seem a lot better approach for passing small quantities of data each frame, and I look forward to use them :)

I will leave things as they are now, but after this pull request gets merged I will research more about the two and change the code for what I see fits it better (so I could explain it latter in the guide).

2022-03-19 18:04 UTC, ZakStar17 commented on chapter_code/src/vulkano_objects/swapchain.rs
> +    .num_images(caps.min_image_count + 1)
Thank you for noticing! This is something I was testing with, and forgot to remove.

One of the tutorials I am following is https://vulkan-tutorial.com and in the [swapchain creation page](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain#page_Creating-the-swap-chain) there is this:

> However, simply sticking to this minimum means that we may sometimes have to wait on the driver to complete internal operations before we can acquire another image to render to. Therefore it is recommended to request at least one more image than the minimum:

I think this somewhat makes sense and I plan to change it. However, this doesn't belong in this pull request, so I will leave it for later.

2022-03-19 18:08 UTC, hakolao commented on chapter_code/src/shaders/movable_square/vertex.glsl
> +} uniforms;
Sounds good!

2022-03-19 18:21 UTC, ZakStar17 commented on chapter_code/src/bin/more_on_buffers/render/render_loop.rs
> +pub struct RenderLoop {
I did this because I think `Renderer` and `RenderLoop` have really different functions, and the multi window ideia just happens to work well with this.

`Renderer` doesn't care about when or how many times it needs to draw, it just contains methods that let it draw some image or change some buffer when his parent asks him to, and doesn't let his parent change its internal members arbitrarily by providing a layer of abstraction.

`RenderLoop` is a example of a parent that implements synchronization, so his job is to know when and what method should be called inside the `Renderer` to produce wanted results each loop. This means that it actually cares about time between draw calls and execution between fences.

2022-03-19 18:27 UTC, hakolao commented on chapter_code/src/bin/more_on_buffers/render/render_loop.rs
> +pub struct RenderLoop {
I have a similar but slightly different approach here: https://github.com/hakolao/bevy_vulkano/blob/master/src/vulkano_window_renderer.rs where basically each window own their renderer. However, the renderer isn't really a renderer, but just has `start_frame` (gives you the previous frame's future) and `end_frame` (give your last future as input) between which the user should create the render commands.

Nice to see your implementation!

2022-03-24 17:45 UTC, merged